"""Persistent observed map knowledge and route execution shared by Systems 1 and 2."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

from pydantic import BaseModel, Field, ValidationError

from nuzlocke.agents.goals import (
    MAX_BURST,
    Goal,
    RoomMap,
    Routes,
    _grid_tiles,
    collision_map,
    map_key,
)
from nuzlocke.environment.terrain import step_delta
from nuzlocke.state.models import GameAction, PlayerObservation


class RoutePlan(BaseModel):
    map_id: int
    objective_key: str = Field(max_length=100)
    waypoints: list[tuple[int, int]] = Field(default_factory=list, max_length=8)
    preference: str = Field(default="safe", pattern="^(safe|shortest)$")
    reason: str = Field(default="", max_length=300)


def parse_route_plan(raw: Any) -> dict:
    try:
        return RoutePlan.model_validate(raw).model_dump(mode="json") if raw else {}
    except (ValidationError, TypeError):
        return {}


def path_tiles(start: tuple[int, int], path: list[str]) -> list[tuple[int, int]]:
    tiles = [start]
    for direction in path:
        dx, dy = step_delta(direction)
        tiles.append((tiles[-1][0] + dx, tiles[-1][1] + dy))
    return tiles


class Navigator:
    """Keep a route until completion, changed objective, or contradictory movement.

    Observed geometry and the vanilla map reference are both supplied to the director.
    Button paths use observed floor, guided toward known destinations in the reference.
    """

    def __init__(self) -> None:
        self.maps: dict[str, dict] = {}
        self.route: dict = {}
        self.plan: dict = {}
        self.last_plan: dict = {}
        self.reason = "No route yet"
        self.replans = 0
        self.reused = 0
        self.rejected_waypoints = 0
        self.brief: dict = {}

    def snapshot(self) -> dict:
        return deepcopy(self.__dict__)

    def restore(self, data: dict) -> None:
        for key in self.__dict__:
            if key in data:
                setattr(self, key, deepcopy(data[key]))

    def observe(self, obs: PlayerObservation, room: RoomMap) -> None:
        if obs.map_id is None or obs.in_battle or obs.cutscene:
            return
        data = self.maps.setdefault(str(obs.map_id), {"grass": [], "warps": [], "size": {}})
        data.update(name=obs.map_name, size=obs.map_size or data["size"])
        if obs.warps:
            data["warps"] = obs.warps
        data["grass"] = sorted(
            {tuple(t) for t in data["grass"]} | {(t["x"], t["y"]) for t in obs.grass_tiles}
        )
        room.costs = {}
        searching = obs.policy.get("encounter_search", False)
        poisoned = any(str(m.get("status", "")).startswith("PSN") for m in obs.party)
        # Poison favors fewer steps to healing. Unknown terrain stays more expensive.
        if not searching and not poisoned and self.plan.get("preference", "safe") == "safe":
            room.costs = {tuple(t): 4 for t in data["grass"]}

    def select(
        self,
        obs: PlayerObservation,
        room: RoomMap,
        goals: list[Goal],
        *,
        objective_text: str | None,
        plan: dict | None = None,
        failed: bool = False,
    ) -> Goal | None:
        goal = next((g for g in goals if g.objective), None)
        if goal is None or goal.kind in {"wait", "explore", "heading"}:
            self.route = {}
            self.brief = {}
            return None
        if not goal.actions and not goal.path:
            self.route = {}
            self.brief = {}
            self.reason = "Objective has no legal route; director must replan"
            return None
        signature = [obs.map_id, goal.key, objective_text, goal.finish]
        if self.route.get("signature") != signature:
            self.route = {}
            self.plan = {}
            self.reason = "Objective or map changed"
        proposed = parse_route_plan(plan)
        if proposed and proposed != self.last_plan:
            self.last_plan = deepcopy(proposed)
            if proposed["map_id"] == obs.map_id and proposed["objective_key"] == goal.key:
                self.plan = deepcopy(proposed)
                self.route = {}
                self.reason = "System 2 updated the route"
        self.observe(obs, room)
        start = (obs.x, obs.y)
        walkable = collision_map(obs, room) or {}
        from nuzlocke.knowledge.map_reference import ledge_jumps

        jumps = ledge_jumps(obs, room)
        remaining = None
        suffix: list[str] = []
        if self.route and not failed:
            tiles = [tuple(t) for t in self.route["tiles"]]
            if start in tiles[:-1]:
                at = tiles.index(start)
                candidate = self.route["path"][at:]
                suffix = self.route["suffix"]
                # Terminal interaction/warp steps were generated by build_goals.
                interior = path_tiles(start, candidate)[1:]
                checked = interior[:-1] if self.route["terminal"] else interior
                edges = room.blocked_edges(obs)
                traversed = list(zip(path_tiles(start, candidate), candidate))
                if all(walkable.get(t, False) for t in checked) and not any(
                    (tile[0], tile[1], d.removeprefix("jump_")) in edges
                    or (d.startswith("jump_") and (*tile, d.removeprefix("jump_")) not in jumps)
                    for tile, d in traversed
                ):
                    remaining = candidate
                    self.reused += 1
                    self.reason = "Continuing verified route"
        if remaining is None:
            self.replans += 1
            if failed:
                self.reason = "Movement blocked; recomputed route"
            elif self.route:
                self.reason = "Route completed or changed; recomputed route"
            remaining = list(goal.path)
            suffix = [goal.finish.value] if goal.finish else []
            # System 2 waypoints are map coordinates, checked against the actual graph.
            waypoints = self.plan.get("waypoints", [])
            while waypoints and tuple(waypoints[0]) == start:
                waypoints.pop(0)
            if waypoints:
                waypoint = tuple(waypoints[0])
                routes = Routes(
                    start,
                    walkable,
                    costs=room.costs,
                    blocked_edges=room.blocked_edges(obs),
                    crossed_edges=room.crossed_edges.get(map_key(obs), set()),
                    terrain_edges=room.terrain_edges(obs),
                    jumps=jumps,
                )
                observed = {**room.known.get(map_key(obs), {}), **_grid_tiles(obs)}
                path = (
                    routes.paths.get(waypoint)
                    if observed.get(waypoint) or waypoint in room.seen(obs)
                    else None
                )
                if path:
                    remaining, suffix = path, []
                    self.reason = "Following System 2 waypoint"
                else:
                    self.rejected_waypoints += 1
                    self.plan["waypoints"] = []
                    self.reason = "Unreachable waypoint rejected; using objective route"
            self.route = {
                "signature": signature,
                "path": remaining,
                "tiles": path_tiles(start, remaining),
                "suffix": suffix,
                "terminal": not self.plan.get("waypoints")
                and (goal.kind in {"exit", "edge", "talk"} or goal.finish is not None),
            }
        if not remaining:
            self.brief = {
                "objective_key": goal.key,
                "destination": objective_text or goal.label,
                "remaining_steps": 0,
                "reason": "No reachable route; awaiting replan",
            }
            return None
        actions = [GameAction(f"walk_{d.removeprefix('jump_')}") for d in remaining[:MAX_BURST]]
        if len(remaining) <= MAX_BURST:
            actions += [GameAction(a) for a in suffix]
        self.brief = {
            "objective_key": goal.key,
            "destination": objective_text or goal.label,
            "remaining_steps": len(remaining),
            "next_waypoint": path_tiles(start, remaining[:MAX_BURST])[-1],
            "preference": self.plan.get("preference", "safe"),
            "reason": self.reason,
            "replan_when": [
                "map or objective changes",
                "next edge blocked",
                "healing or battle interrupts",
            ],
        }
        # First selection goes through Jev; later verified segments execute directly.
        return Goal(
            key=goal.key,
            kind=goal.kind,
            label=goal.label,
            actions=actions,
            facts=[*goal.facts, f"persistent route: {len(remaining)} steps remain"],
            path=remaining,
            objective=True,
        )

    def context(self, obs: PlayerObservation, room: RoomMap, objective: dict | None = None) -> dict:
        from nuzlocke.knowledge.map_reference import briefing
        from nuzlocke.knowledge.objects import object_facts

        data = self.maps.get(str(obs.map_id), {})
        known = room.known.get(map_key(obs), {})
        seen = room.seen(obs)
        size = obs.map_size or data.get("size") or {}
        w, h = min(size.get("w", 0), 130), min(size.get("h", 0), 130)
        grass = {tuple(t) for t in data.get("grass", [])}
        rows = []
        for y in range(h):
            row = []
            for x in range(w):
                t = (x, y)
                c = "." if known.get(t) or t in seen else "#" if t in known else "?"
                if t in grass:
                    c = ","
                if t == (obs.x, obs.y):
                    c = "@"
                row.append(c)
            rows.append("".join(row))
        return {
            "map_id": obs.map_id,
            "map": obs.map_name,
            "player": [obs.x, obs.y],
            "size": size,
            "source": "observed grid and verified walks; unknown terrain is ?",
            "legend": "x=column, y=row (zero based); @ player, . open, # wall, ? unknown, , grass",
            "rows": rows,
            "reference_map": briefing(obs, objective, room),
            "warps": obs.warps or data.get("warps", []),
            "objects": [object_facts(obs, npc) for npc in obs.npcs],
            "signs": obs.signs,
            "interaction_target": objective
            if objective and objective.get("kind") in {"npc", "face"}
            else None,
            "temporary_blocked_edges": [list(e) for e in room.temporary_edges(obs)],
            "terrain_blocked_edges": [list(e) for e in sorted(room.terrain_edges(obs))],
            "route": self.brief,
            "path": self.route.get("tiles", [])
            if self.route.get("signature", [None])[0] == obs.map_id
            else [],
            "replans": self.replans,
            "reused_segments": self.reused,
            "rejected_waypoints": self.rejected_waypoints,
        }
